### ISSUE TITLE
안구 질환 분류 AI 모델

### ISSUE THREAD

**Issue by ryugibo** [pal-ette/iPetPal#5]
- [x] CNN 하이퍼파라미터 조정

**Comment by ryugibo** [comment]
https://github.com/NielsRogge/Transformers-Tutorials/blob/master/VisionTransformer/Fine_tuning_the_Vision_Transformer_on_CIFAR_10_with_the_%F0%9F%A4%97_Trainer.ipynb

**Comment by doctorpeppercokebear** [comment]
05/17 TODO

- [ ]  CNN 하이퍼파라미터 조정
- [ ] VIT 모델 완성

**Comment by ryugibo** [comment]
@doctorpeppercokebear /cc @mj0410 
train, validation 데이터 셋이 이미 폴더로 분리되어있어서 validation_split이 설정되면 안됨

https://github.com/pal-ette/iPetPal/blob/6e2396c0d5cf09a90dac162f5e84e0ef2868227c/models/Resnet50v2_squared.ipynb#L192-L205

**Comment by doctorpeppercokebear** [comment]
05/30 todo

- [ ] 검안경 으로 촬영한 데이터가 포함된 데이터셋 augumentation 적용 후 언더샘플링 징행
- [ ]  만들어진 데이터셋으로 ResNet50 모델 학습
